# Generated by Django 5.2.7 on 2025-11-27 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('exchange', 'صرافی'), ('fuel_tank', 'تانک تیل')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_af', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_af', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manager', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'واریز'), ('withdrawal', 'برداشت')], max_length=20)),
                ('amount_af', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.account')),
            ],
        ),
    ]
