# Generated by Django 5.2.7 on 2025-11-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_total_deposit_af_account_total_deposit_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Exchange', 'صرافی'), ('Tank', 'تانک تیل')], max_length=20),
        ),
    ]
